horizontal_menu: main
horizontal_depth: 9
off_canvas_menus: main
horizontal_wrapping_element: nav
horizontal_breakpoint: wide
horizontal_media_query: 'all and (min-width: 851px)'
include_css: false
off_canvas_position: right
off_canvas_theme: theme-dark
pagedim: pagedim
horizontal_superfish: false
horizontal_superfish_delay: 300
horizontal_superfish_speed: 100
horizontal_superfish_speed_out: 100
horizontal_superfish_hoverintent: true
hammerjs: false
breakpoint_css_filepath: 'public://css'
use_breakpoint: true
allow_admin: false
wrapper_admin: true
wrapper_theme: false
extension_keyboard: true
_core:
  default_config_hash: U7p9WqE0yMw-SNTivefWcS3D61GPAcUrlQxPCm4mYxQ
